# ../md-to-pdf-plugins/hierarchy-table/hierarchy-table.config.yaml
description: "Plugin to display a Markdown table as a presentation slide, ideal for hierarchies or structured data."
handler_script: "index.js"
css_files:
  - "hierarchy-table.css"

pdf_options:
  landscape: true
  # For a 16:9 aspect ratio slide on Letter paper (approx):
  # width: "11in"
  # height: "6.1875in" 
  # Or, using a standard format and adjusting margins:
  format: "Letter" # Results in 11in x 8.5in in landscape
  margin:
    top: "0.5in"
    bottom: "0.5in"
    left: "0.5in"
    right: "0.5in"
  printBackground: true

inject_fm_title_as_h1: false
aggressiveHeadingCleanup: false
math:
  enabled: false 
